export const Details=[
    {
       image:"https://cdn.staticmb.com/property/microsite/mb-banners/00668658/feature-project/img.jpg",
       title: "Bhaggyam Athulya",
       limit: "Marketed by Bhaggyam Constructions Pvt",
       area: "Sholinganallur",
       space: "3 BHK Flats",
       img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdNupqYLQqiaixZSJf-ws0n165j0EhXFkV7fka0T965Q&usqp=CAU&ec=48665699",
       Amount:"₹ 30.0 Lac",
       Loan:"Get ₹9,000 cashback on Home Loan",
       Bhk:"2BHK Builder Floor For Sale in",
       Location:"MGR Nager-East,Chennai",
       Beds:"2Beds",
       Baths:"2Baths",
       Balcony:"1Balcony",
       Covered:"1Covered Parking",
       CarpetArea:"500sqft",
       Floor:"1(Out of 4Floors)",
       Transcationtype:"New Property",
       Status:"Ready to Move",
       Facing:"North-East",
       Lift:"1",
       FurnishedStatus:"Furnished",
       Carparking:"1Covered",
       TypeOfOwnership:"Freehold",
       Newly:"Newly Constructed Property",
       Button:"Contact Agent",
       Button1:"Get Phone No",
       Last:"Last contact made 5 days ago",
       More:"More Details",
       PriceBreakup:"₹30 Lac | ₹2,10,000 Approx. Registration Charges",
       BookingAmount:"₹21,000",
       Address:"MGR Nager-East,Chennai",
       Landmarks:"Bustand",
       Furnishing:"Furnished",
       Flooring:"Vitrified",
       LoanOffered:"Estimated EMI: ₹15,533 Apply for Home Loan",
       TypeofOwnership:"Freehold",
       Overlooking:"Main Road",
       AgeofConstruction:"New Construction",
       WaterAvailability:"24 Hours Available",
       StatusofElectricity:"No/Rare Powercut",   
       Lift:"1",
       AuthorityApproval:"Developer",
       },
   
       {
        image:
           "https://cdn.staticmb.com/property/microsite/mb-banners/00776087/featureproject-img.jpg",
         title: "Pearl Queens Park",
         name: "Pearl Constructions",
         area: "Medavakkam",
         space: "2, 3 BHK Flats",
         limit: "Marketed by Pearl Constructions",
       img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdNupqYLQqiaixZSJf-ws0n165j0EhXFkV7fka0T965Q&usqp=CAU&ec=48665699",
       Amount:"₹ 37.0 Lac",
       Loan:"Get ₹11,096 cashback on Home Loan",
       Bhk:" BHK 765 Sq-ft Flat For Sale",
       Location:"Siruseri, Chennai",
       Beds:"2Beds",
       Baths:"2Baths",
       Balcony:"1Balcony",
       Covered:"1Covered Parking",
       CarpetArea:"765sqft",
       Floor:"1(Out of 4Floors)",
       Transcationtype:"New Property",
       Status:"Ready to Move",
       Facing:"South",
       Lift:"2",
       FurnishedStatus:"Unfurnished",
       Carparking:"1Covered",
       TypeOfOwnership:"Freehold",
       Newly:"OFFER 18 Months No Pre EMI",
       Button:"Contact Agent",
       Button1:"Get Phone No",
       Last:"Last contact made 2 days ago",
       More:"More Details",
       PriceBreakup:"₹37 Lac",
       BookingAmount:"₹50,000",
       Address:"Siruseri, Chennai - South, Tamil Nadu",
       Furnishing:"Unfurnished",
       Flooring:"Vitrified",
       LoanOffered:"Estimated EMI: ₹19,151 Apply for Home Loan",
       TypeofOwnership:"Freehold",
       AgeofConstruction:"New Construction",
       WaterAvailability:"24 Hours Available",
       StatusofElectricity:"No/Rare Powercut",   
       Lift:"2",
       AuthorityApproval:"Developer",
       },
   
       {
       image:
           "https://cdn.staticmb.com/property/microsite/mb-banners/00738636/featureproject-img.jpg",
         title: "Nest Craft",
         name: "Nest Builders",
         area: "Sithalapakkam",
         space: "2,3 BHK Flat",
         limit: "Marketed by Nest Builders",
       img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdNupqYLQqiaixZSJf-ws0n165j0EhXFkV7fka0T965Q&usqp=CAU&ec=48665699",
       Amount:"₹ 23.5 Lac",
       Loan:"Get ₹7,053 cashback on Home Loan",
       Bhk:"2BHK Builder Floor For Sale in",
       Location:"T Nager West,Chennai",
       Beds:"2Beds",
       Baths:"2Baths",
       Balcony:"1Balcony",
       Covered:"1Covered Parking",
       CarpetArea:"540sqft",
       Floor:"1(Out of 4Floors)",
       Transcationtype:"New Property",
       Status:"Ready to Move",
       Facing:"North",
       Lift:"1",
       FurnishedStatus:"Furnished",
       Carparking:"2Covered",
       TypeOfOwnership:"Freehold",
       Newly:"Newly Constructed Property",
       Button:"Contact Agent",
       Button1:"Get Phone No",
       Last:"Last contact made 34 days ago",
       More:"More Details",
       PriceBreakup:"₹23 Lac",
       BookingAmount:"₹11,000",
       Address:"T Nager West,Chennai",
       Landmarks:"Dwarka mor",
       Furnishing:"Semi-Furnished",
       Flooring:"Vitrified, Marble, Granite",
       LoanOffered:"Estimated EMI: ₹12,173 Apply for Home Loan",
       TypeofOwnership:"Freehold",
       Overlooking:"Garden/Park, Main Road",
       AgeofConstruction:"New Construction",
       WaterAvailability:"24 Hours Available",
       StatusofElectricity:"No/Rare Powercut",   
       Lift:"1",
       AuthorityApproval:"Municipal Corporation of Delhi",
       },
   
       {
        image:
           "https://cdn.staticmb.com/property/microsite/mb-banners/00813495/featureproject-img.jpg",
         title: "Tulive Azpire",
         name: "Tulive GK Shetty",
         area: "Mudichur",
         space: "2, 3 BHK Flats",
         limit: "Marketed by Tulive GK Shetty",
       img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdNupqYLQqiaixZSJf-ws0n165j0EhXFkV7fka0T965Q&usqp=CAU&ec=48665699",
       Amount:"₹ 27.0 Lac",
       Loan:"Get ₹8,100 cashback on Home Loan",
       Bhk:"2BHK Builder Floor For Sale in",
       Location:"Adyar,Chennai",
       Beds:"2Beds",
       Baths:"2Baths",
       Balcony:"1Balcony",
       Covered:"1Covered Parking",
       CarpetArea:"600sqft",
       Floor:"1(Out of 4 Floors)",
       Transcationtype:"New Property",
       Status:"Ready to Move",
       Facing:"East",
       Lift:"1",
       FurnishedStatus:"Semi-Furnished",
       Carparking:"2Covered",
       TypeOfOwnership:"Freehold",
       Newly:"Newly Constructed Property",
       Button:"Contact Agent",
       Button1:"Get Phone No",
       Last:"Last contact made 63 days ago",
       More:"More Details",
       PriceBreakup:"₹27 Lac | ₹1,89,000 Approx. Registration Charges",
       BookingAmount:"₹15,000",
       Address:"Adyar,Chennai",
       Landmarks:"BusStop-West",
       Furnishing:"Semi-Furnished",
       Flooring:"Vitrified, Marble, Granite",
       LoanOffered:"Estimated EMI: ₹12,173 Apply for Home Loan",
       TypeofOwnership:"Freehold",
       Overlooking:"Garden/Park, Main Road",
       AgeofConstruction:"New Construction",
       WaterAvailability:"24 Hours Available",
       StatusofElectricity:"No/Rare Powercut",   
       Lift:"1",
       AuthorityApproval:"Municipal Corporation of Delhi",
       },
   
       {
       image:
           "https://cdn.staticmb.com/property/microsite/mb-banners/00820966/featureproject-img.jpg",
         title: "S.I.S Capetown",
         name: "South India Shelters Pvt Ltd",
         area: "Surapet",
         space: "Residential Plots",
         limit: "Marketed by South India Shelters Pvt Ltd",
       img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdNupqYLQqiaixZSJf-ws0n165j0EhXFkV7fka0T965Q&usqp=CAU&ec=48665699",
       Amount:"₹ 72.0 Lac",
       Loan:"Get ₹21,600 cashback on Home Loan",
       Bhk:"3BHK Builder Floor For Sale in Hindh Homes",
       Location:"R.A Puram,Chennai",
       Beds:"3Beds",
       Baths:"3Baths",
       Balcony:"1Balcony",
       Covered:"1Covered Parking",
       CarpetArea:"1250sqft",
       Floor:"2(Out of 4Floors)",
       Transcationtype:"New Property",
       Status:"Ready to Move",
       Facing:"South",
       Lift:"2",
       FurnishedStatus:"Unfurnished",
       Carparking:"2Covered",
       TypeOfOwnership:"Freehold",
       Newly:"Newly Constructed Property",
       Button:"Contact Agent",
       Button1:"Get Phone No",
       Last:"Last contact made 10 days ago",
       More:"More Details",
       PriceBreakup:"₹72 Lac",
       BookingAmount:"₹50,000",
       Address:"R.A Puram,Chennai",
       AdditionalRooms:"Puja Room",
       Furnishing:"Unfurnished",
       AgeofConstruction:"New Construction",
       WaterAvailability:"24 Hours Available",
       StatusofElectricity:"No/Rare Powercut",   
       Lift:"2",
       },
   
       {
       image:
           "https://cdn.staticmb.com/property/microsite/mb-banners/00816805/featureproject-img.jpg",
         title: "Vtech Arputha",
         name: "VTECH BUILDER",
         area: "Sithalapakkam",
         space: "2,3 BHK Flats",
         limit: "Marketed by Vtech Builder",
       img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdNupqYLQqiaixZSJf-ws0n165j0EhXFkV7fka0T965Q&usqp=CAU&ec=48665699",
       Amount:"₹48.4 Lac",
       Loan:"Get ₹14,520 cashback on Home Loan",
       Bhk:"3 BHK 1200 Sq-ft Flat For Sale",
       Location:"Ottiambakkam, Chennai",
       Beds:"3Beds",
       Baths:"2Baths",
       Balcony:"1Balcony",
       Covered:"1Covered Parking",
       CarpetArea:"1200sqft",
       Floor:"2(Out of 4Floors)",
       Transcationtype:"New Propery",
       Status:"Under Construction",
       Facing:"North",
       Lift:"2",
       FurnishedStatus:"Unfurnished",
       Carparking:"2Covered",
       TypeOfOwnership:"Freehold",
       Button:"Contact Agent",
       Button1:"Get Phone No",
       Last:"Last contact made 30 days ago",
       More:"More Details",
       PriceBreakup:"₹48.4 Lac",
       BookingAmount:"₹1Lac",
       Address:"Ottiambakkam, Chennai - South, Tamil Nadu",
       Furnishing:"Unfurnished",
       AgeofConstruction:"New Construction",
       WaterAvailability:"24 Hours Available",
       StatusofElectricity:"No/Rare Powercut",   
       Lift:"2",
       },
       
        {
       img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdNupqYLQqiaixZSJf-ws0n165j0EhXFkV7fka0T965Q&usqp=CAU&ec=48665699",
       Amount:"₹ 62.0 Lac",
       Loan:"Get ₹18,600 cashback on Home Loan",
       Bhk:"3BHK Builder Floor For Sale in",
       Location:"Chennai",
       Beds:"3Beds",
       Baths:"3Baths",
       Balcony:"1Balcony",
       Covered:"1Covered Parking",
       CarpetArea:"1000sqft",
       Floor:"1(Out of 4Floors)",
       Transcationtype:"New Property",
       Status:"Ready to Move",
       Facing:"North-East",
       Lift:"1",
       FurnishedStatus:"Furnished",
       Carparking:"1Covered",
       TypeOfOwnership:"Freehold",
       Button:"Contact Agent",
       Button1:"Get Phone No",
       Last:"Last contact made 15 days ago",
       More:"More Details",
       PriceBreakup:"₹62 Lac | ₹4,34,000 Approx. Registration Charges",
       BookingAmount:"₹25,000",
       Address:"Chennai",
       Landmarks:"Apollo hospital",
       Furnishing:"Furnished",
       Flooring:"Vitrified",
       LoanOffered:"Estimated EMI: ₹32,102 Apply for Home Loan",
       TypeofOwnership:"Freehold",
       Overlooking:"Main Road",
       AgeofConstruction:"New Construction",
       WaterAvailability:"24 Hours Available",
       StatusofElectricity:"No/Rare Powercut",   
       Lift:"1",
       AuthorityApproval:"Developer",
       },
   
       {
       img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdNupqYLQqiaixZSJf-ws0n165j0EhXFkV7fka0T965Q&usqp=CAU&ec=48665699",
       Amount:"₹ 95.0 Lac",
       Loan:"Get ₹25,800 cashback on Home Loan",
       Bhk:"3BHK Builder Floor For Sale in",
       Location:"Besant Nager,Chennai",
       Beds:"3Beds",
       Baths:"3Baths",
       Balcony:"1Balcony",
       Covered:"1Covered Parking",
       CarpetArea:"1100sqft",
       Floor:"2(Out of 4Floors)",
       Transcationtype:"Resale",
       Status:"Ready to Move",
       Facing:"North-East",
       Lift:"1",
       FurnishedStatus:"Unfurnished",
       Carparking:"1Covered",
       TypeOfOwnership:"Freehold",
       Button:"Contact Agent",
       Button1:"Get Phone No",
       Last:"Last contact made 26 days ago",
       More:"More Details",
       PriceBreakup:"₹95 Lac | ₹6,65,000 Approx. Registration Charges",
       BookingAmount:"₹10Lac",
       Address:"Besant Nager,Chennai",
       Furnishing:"Unfurnished",
       Flooring:"Vitrified",
       TypeofOwnership:"Freehold",
       Overlooking:"Garden/Park",
       AgeofConstruction:"New Construction",
       WaterAvailability:"24 Hours Available",
       StatusofElectricity:"No/Rare Powercut",   
       Lift:"1",
       AuthorityApproval:"Developer",
       },
   
       {
       img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdNupqYLQqiaixZSJf-ws0n165j0EhXFkV7fka0T965Q&usqp=CAU&ec=48665699",
       Amount:"₹1.0Cr",
       Loan:"Get ₹30,000 cashback on Home Loan",
       Bhk:"4BHK Builder Floor For Sale in",
       Location:"Mylapore,Chennai",
       Beds:"4Beds",
       Baths:"3Baths",
       Balcony:"2Balcony",
       Covered:"2Covered Parking",
       CarpetArea:"1400sqft",
       Floor:"2(Out of 3Floors)",
       Transcationtype:"Resale",
       Status:"Ready to Move",
       Facing:"North-East",
       Lift:"NAN",
       FurnishedStatus:"Semi-Furnished",
       Carparking:"1 Open",
       TypeOfOwnership:"Freehold",
       Button:"Contact Agent",
       Button1:"Get Phone No",
       Last:"Last contact made 19 days ago",
       More:"More Details",
       PriceBreakup:"₹1 Cr | ₹8,67,175 Stamp Duty, Registration Charges | ₹700 Monthly",
       BookingAmount:"₹10,Lac",
       Address:"Mylapore,Chennai",
       Furnishing:"Semi-Furnished",
       Flooring:"Marble",
       TypeofOwnership:"Freehold",
       Overlooking:"Garden/Park",
       AgeofConstruction:"New Construction",
       WaterAvailability:"24 Hours Available",
       StatusofElectricity:"No/Rare Powercut",   
       Lift:"NAN",
       },
    
       {
       img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdNupqYLQqiaixZSJf-ws0n165j0EhXFkV7fka0T965Q&usqp=CAU&ec=48665699",
       Amount:"₹1.45Cr",
       Loan:"Get ₹54,340 cashback on Home Loan",
       Bhk:"4BHK Builder Floor For Sale in",
       Location:"Gopalapuram,Chennai",
       Beds:"4Beds",
       Baths:"4Baths",
       Balcony:"2Balcony",
       Covered:"1Covered Parking",
       CarpetArea:"1500sqft",
       Floor:"2(Out of 3Floors)",
       Transcationtype:"Resale",
       Status:"Ready to Move",
       Facing:"East",
       Lift:"2",
       FurnishedStatus:"Unfurnished",
       Carparking:"1 Open",
       TypeOfOwnership:"Freehold",
       Button:"Contact Agent",
       Button1:"Get Phone No",
       Last:"Last contact made 9 days ago",
       More:"More Details",
       PriceBreakup:"₹1.45 Cr",
       BookingAmount:"₹10,Lac",
       Address:"Gopalapuram,Chennai",
       Furnishing:"Unfurnished",
       Flooring:"Marble",
       TypeofOwnership:"Freehold",
       Overlooking:"Park",
       AgeofConstruction:"New Construction",
       WaterAvailability:"24 Hours Available",
       StatusofElectricity:"No/Rare Powercut",   
       Lift:"2",
       },
   
       {
       img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdNupqYLQqiaixZSJf-ws0n165j0EhXFkV7fka0T965Q&usqp=CAU&ec=48665699",
       Amount:"₹1.50Cr",
       Loan:"Get ₹30,000 cashback on Home Loan",
       Bhk:"4 BHK 2185 Sq-ft Flat For Sale",
       Location:"Kolathur, Chennai",
       Beds:"4Beds",
       Baths:"4Baths",
       Balcony:"2Balcony",
       Covered:"1Covered Parking",
       CarpetArea:"2185sqft",
       Floor:"2(Out of 3Floors)",
       Transcationtype:"New Property",
       Status:"Ready to Move",
       Facing:"North",
       Lift:"1",
       FurnishedStatus:"Unfurnished",
       Carparking:"1 Open",
       TypeOfOwnership:"Freehold",
       Button:"Contact Agent",
       Button1:"Get Phone No",
       Last:"Last contact made 2 days ago",
       More:"More Details",
       PriceBreakup:"₹1.5 Cr",
       BookingAmount:"₹20,Lac",
       Address:"Kolathur, Chennai - Central, Tamil Nadu",
       Furnishing:"Unfurnished",
       Flooring:"Marble",
       TypeofOwnership:"Freehold",
       Overlooking:"Main Road",
       AgeofConstruction:"New Construction",
       WaterAvailability:"24 Hours Available",
       StatusofElectricity:"No/Rare Powercut",   
       Lift:"1",
       },
   
   
       {
       img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdNupqYLQqiaixZSJf-ws0n165j0EhXFkV7fka0T965Q&usqp=CAU&ec=48665699",
       Amount:"₹ 59.0 Lac",
       Loan:"Get ₹17,970 cashback on Home Loan",
       Bhk:"4BHK Builder Floor For Sale in",
       Location:"Thiruvanmiyur,Chennai",
       Beds:"4Beds",
       Baths:"3Baths",
       Balcony:"2Balcony",
       Covered:"2Covered Parking",
       CarpetArea:"446sqft",
       Floor:"2(Out of 2Floors)",
       Transcationtype:"Resale",
       Status:"Ready to Move",
       Facing:"East",
       Lift:"1",
       FurnishedStatus:"Unfurnished",
       Carparking:"1Covered",
       TypeOfOwnership:"Freehold",
       Newly:"East Facing Property",
       Button:"Contact Agent",
       Button1:"Get Phone No",
       Last:"Last contact made 2 days ago",
       More:"More Details",
       PriceBreakup:"₹59 Lac",
       Address:"Thiruvanmiyur,Chennai",
       Landmarks:"Goverment School",
       Furnishing:"Unfurnished",
       Flooring:"Vitrified,Ceramic Tiles",
       TypeofOwnership:"Freehold",
       Overlooking:"Main Road",
       AgeofConstruction:"Less than 5 years",
       WaterAvailability:"24 Hours Available",
       StatusofElectricity:"No/Rare Powercut",   
       Lift:"1",
       },
       
       {
       img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdNupqYLQqiaixZSJf-ws0n165j0EhXFkV7fka0T965Q&usqp=CAU&ec=48665699",
       Amount:"₹ 1.0 Cr",
       Loan:"Get ₹30,000 cashback on Home Loan",
       Bhk:"5BHK Builder Floor For Sale in",
       Location:"Nungambakkam, Chennai",
       Beds:"5Beds",
       Baths:"4Baths",
       Balcony:"3Balcony",
       Covered:"2Covered Parking",
       CarpetArea:"1200sqft",
       Floor:"4(Out of 4 Floors)",
       Transcationtype:"New Property",
       Status:"Ready to Move",
       Facing:"North",
       Lift:"1",
       FurnishedStatus:"Semi-Furnished",
       Carparking:"1 Covered 1 Open",
       TypeOfOwnership:"Freehold",
       Newly:"Newly Constructed Property",
       Button:"Contact Agent",
       Button1:"Get Phone No",
       Last:"Last contact made 11 days ago",
       More:"More Details",
       PriceBreakup:"₹1 Cr | ₹7,00,000 Approx. Registration Charges | ₹100 Monthly",
       BookingAmount:"₹10.0Lac",
       Address:"Nungambakkam,Chennai",
       Landmarks:"Main Road",
       Furnishing:"Semi-Furnished",
       Flooring:"Marble, Normal Tiles/Kotah Stone",
       LoanOffered:"Estimated EMI: ₹51,778 Apply for Home Loan",
       TypeofOwnership:"Freehold",
       Overlooking:"Park,Main Road",
       AgeofConstruction:"New Construction",
       WaterAvailability:"24 Hours Available",
       StatusofElectricity:"No/Rare Powercut",   
       Lift:"1",
       AuthorityApproval:"Development Authority",
       },
   
       {
       img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdNupqYLQqiaixZSJf-ws0n165j0EhXFkV7fka0T965Q&usqp=CAU&ec=48665699",
       Amount:"₹ 85.0 Lac",
       Loan:"Get ₹25,000 cashback on Home Loan",
       Bhk:"5BHK Builder Floor For Sale in",
       Location:"Boat Club, Chennai",
       Beds:"5Beds",
       Baths:"4Baths",
       Balcony:"2Balcony",
       Covered:"1Covered Parking",
       CarpetArea:"1200sqft",
       Floor:"4(Out of 4 Floors)",
       Transcationtype:"New Property",
       Status:"Ready to Move",
       Facing:"North-East",
       Lift:"1",
       FurnishedStatus:"Semi-Furnished",
       Carparking:"1 Covered 1 Open",
       TypeOfOwnership:"Freehold",
       Newly:"Newly Constructed Property",
       Button:"Contact Agent",
       Button1:"Get Phone No",
       Last:"Last contact made 2 days ago",
       More:"More Details",
       PriceBreakup:"₹85 Lac | ₹5,95,000 Approx. Registration Charges | ₹200 Monthly",
       BookingAmount:"₹10.0Lac",
       Address:"Boat Club,Chennai",
       Landmarks:"BusStand",
       Furnishing:"Semi-Furnished",
       Flooring:"Marble, Normal Tiles/Kotah Stone",
       LoanOffered:"Estimated EMI: ₹42,012 Apply for Home Loan",
       TypeofOwnership:"Freehold",
       Overlooking:"Garden/Park,Main Road",
       AgeofConstruction:"New Construction",
       WaterAvailability:"24 Hours Available",
       StatusofElectricity:"No/Rare Powercut",   
       Lift:"1",
       AuthorityApproval:"Development Authority",
       },
   
       {
       img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdNupqYLQqiaixZSJf-ws0n165j0EhXFkV7fka0T965Q&usqp=CAU&ec=48665699",
       Amount:"₹ 1.30 Cr",
       Loan:"Get ₹39,000 cashback on Home Loan",
       Bhk:"5 BHK 2200 Sq-ft Flat For Sale",
       Location:"Korattur, Chennai",
       Beds:"5Beds",
       Baths:"3Baths",
       Balcony:"2Balcony",
       Covered:"1Covered Parking",
       CarpetArea:"1800sqft",
       Floor:"14(Out of 17 Floors)",
       Transcationtype:"New Property",
       Status:"Ready to Move",
       Facing:"West",
       Lift:"1",
       FurnishedStatus:"Unfurnished",
       Carparking:"1 Covered 1 Open",
       TypeOfOwnership:"Freehold",
       Newly:"Newly Constructed Property",
       Button:"Contact Agent",
       Button1:"Get Phone No",
       Last:"Last contact made 4 days ago",
       More:"More Details",
       PriceBreakup:"₹1.3 Cr | ₹10,40,000 Approx. Registration Charges",
       BookingAmount:"₹15.0Lac",
       Address:"korature, Korattur, Chennai - North, Tamil Nadu",
       Landmarks:"VR Mall",
       Furnishing:"Unfurnished",
       Flooring:"Granite, Normal Tiles/Kotah Stone, Marble, Ceramic Tiles, Wooden, Vitrified, Mosaic, Marbonite",
       LoanOffered:"Estimated EMI: ₹67,312 Apply for Home Loan",
       TypeofOwnership:"Freehold",
       Overlooking:"Pool,Garden/Park",
       AgeofConstruction:"New Construction",
       WaterAvailability:"24 Hours Available",
       StatusofElectricity:"No/Rare Powercut",   
       Lift:"1",
       AuthorityApproval:"Developer",
       },
   
       {
       img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdNupqYLQqiaixZSJf-ws0n165j0EhXFkV7fka0T965Q&usqp=CAU&ec=48665699",
       Amount:"₹ 10.0 Lac",
       Loan:"Get ₹3,000 cashback on Home Loan",
       Bhk:"1BHK Builder Floor For Sale in",
       Location:"Royapettah,Chennai",
       Beds:"1Beds",
       Baths:"1Baths",
       CarpetArea:"390sqft",
       Floor:"1(Out of 4 Floors)",
       Transcationtype:"New Property",
       Status:"Ready to Move",
       Facing:"North-East",
       Lift:"1",
       FurnishedStatus:"Semi-Furnished",
       Carparking:"1 Open",
       TypeOfOwnership:"Freehold",
       Newly:"Newly Constructed Property",
       Button:"Contact Agent",
       Button1:"Get Phone No",
       Last:"Last contact made 10 days ago",
       More:"More Details",
       PriceBreakup:"₹10 Lac | ₹70,000 Approx. Registration Charges | ₹50 Monthly",
       BookingAmount:"₹11.000",
       Address:"Royapettah, Chennai",
       Landmarks:"Mani Road,Chennai",
       Furnishing:"Semi-Furnished",
       Flooring:"Mosaic, Vitrified, Ceramic Tiles, Marble, Granite, Marbonite",
       LoanOffered:"Estimated EMI: ₹5,177 Apply for Home Loan",
       TypeofOwnership:"Freehold",
       Overlooking:"Park,Main Road",
       AgeofConstruction:"New Construction",
       WaterAvailability:"24 Hours Available",
       StatusofElectricity:"No/Rare Powercut",   
       Lift:"1",
       AuthorityApproval:"Developer",
       },
     
       {
       img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdNupqYLQqiaixZSJf-ws0n165j0EhXFkV7fka0T965Q&usqp=CAU&ec=48665699",
       Amount:"₹ 8.3 Lac",
       Loan:"Get ₹2,475 cashback on Home Loan",
       Bhk:"1 BHK Flat For Sale in Arun Excello Compact Homes",
       Location:"Padapai, Chennai",
       Beds:"1Beds",
       Baths:"1Baths",
       CarpetArea:"375sqft",
       Floor:"1(Out of 4Floors)",
       Transcationtype:"Resale",
       Status:"Ready to Move",
       Facing:"North",
       AgeofConstruction:"5 to 10 years",
       Developer:"Arun Excello",
       Carparking:"1Covered",
       TypeOfOwnership:"Freehold",
       Button:"Contact Agent",
       Button1:"Get Phone No",
       Last:"Last contact made 10 days ago",
       More:"More Details",
       PriceBreakup:"₹8.3 Lac",
       BookingAmount:"₹10,000",
       Address:"Arun excello compact homes - vasanthaa - block no. 1, flat no. F-43, 1st floor, karanaithangal, padappai, chennai south - chennai, Padapai, Chennai - Outer South, Tamil Nadu",
       Landmarks:"Main Road,Padapai",
       Furnishing:"Unfurnished",
       LoanOffered:"Estimated EMI: ₹4,271 Apply for Home Loan",
       TypeofOwnership:"Freehold",
       Overlooking:"Main Road",
       AgeofConstruction:"5 to 10 years",
       WaterAvailability:"24 Hours Available",
       StatusofElectricity:"No/Rare Powercut",   
       },
   
       {
       img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdNupqYLQqiaixZSJf-ws0n165j0EhXFkV7fka0T965Q&usqp=CAU&ec=48665699",
       Amount:"₹ 9.5 Lac",
       Loan:"Get ₹2,850 cashback on Home Loan",
       Bhk:"1BHK For Sale in",
       Location:"Maduranthakam, Chennai",
       Beds:"1Beds",
       Baths:"1Baths",
       CarpetArea:"350sqft",
       Floor:"1(Out of 4Floors)",
       Transcationtype:"New Property",
       Status:"Ready to Move",
       Facing:"North",
       FurnishedStatus:"Unfurnished",
       Carparking:"1Covered",
       TypeOfOwnership:"Freehold",
       Button:"Contact Agent",
       Button1:"Get Phone No",
       Last:"Last contact made 8 days ago",
       More:"More Details",
       PriceBreakup:"₹9.5 Lac",
       BookingAmount:"₹10,000",
       Address:"Perumbakkam, Maduranthagam, Maduranthakam, Chennai - Outer South, Tamil Nadu",
       Landmarks:"Between Vedanthangal and Maduranthagam",
       Furnishing:"Unfurnished",
       Flooring:"Normal Tiles/Kotah Stone",
       TypeofOwnership:"Freehold",
       Overlooking:"Main Road",
       AgeofConstruction:"New Construction",
       WaterAvailability:"24 Hours Available",
       StatusofElectricity:"No/Rare Powercut",   
       AuthorityApproval:"Developer",
       },
       
       {
       img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdNupqYLQqiaixZSJf-ws0n165j0EhXFkV7fka0T965Q&usqp=CAU&ec=48665699",
       Amount:"₹ 10.0 Lac",
       Loan:"Get ₹3,000 cashback on Home Loan",
       Bhk:"1BHK Owner Residential House For Sale",
       Location:"Teeds Garden, Chennai",
       Beds:"1Beds",
       Baths:"1Baths",
       CarpetArea:"180sqft",
       Floor:"1(Out of 4Floors)",
       Transcationtype:"Resale",
       Status:"Ready to Move",
       Facing:"North-West",
       FurnishedStatus:"Unfurnished",
       Carparking:"1Covered",
       TypeOfOwnership:"Freehold",
       Button:"Contact Agent",
       Button1:"Get Phone No",
       Last:"Last contact made 3 days ago",
       More:"More Details",
       PriceBreakup:"₹10 Lac | ₹80,000 Approx. Registration Charges",
       BookingAmount:"₹1.0 Lac",
       Address:"715 thillainayagam 5th Street, perambur, chennai 11 near s2 cinemas, Teeds Garden, Chennai - North, Tamil Nadu",
       Landmarks:"Mosque",
       Furnishing:"Unfurnished",
       Flooring:"Normal Tiles/Kotah Stone",
       TypeofOwnership:"Freehold",
       Overlooking:"Main Road",
       AgeofConstruction:"5 to 10 years",
       WaterAvailability:"24 Hours Available",
       StatusofElectricity:"No/Rare Powercut",   
       AuthorityApproval:"Developer",
       },
   
        {
       img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdNupqYLQqiaixZSJf-ws0n165j0EhXFkV7fka0T965Q&usqp=CAU&ec=48665699",
       Amount:"₹ 15.0 Lac",
       Loan:"Get ₹5,380 cashback on Home Loan",
       Bhk:"1BHK Owner Residential House For Sale",
       Location:"Anna Nager,Chennai",
       Beds:"1Beds",
       Baths:"1Baths",
       CarpetArea:"230sqft",
       Floor:"1(Out of 4Floors)",
       Transcationtype:"Resale",
       Status:"Ready to Move",
       Facing:"West",
       FurnishedStatus:"Furnished",
       Carparking:"1Covered",
       TypeOfOwnership:"Freehold",
       Button:"Contact Agent",
       Button1:"Get Phone No",
       Last:"Last contact made 20 days ago",
       More:"More Details",
       PriceBreakup:"₹15 Lac",
       BookingAmount:"₹3.0 Lac",
       Address:"Anna Nager,Chennai",
       Landmarks:"Main Road",
       Furnishing:"Furnished",
       Flooring:"Normal Tiles",
       TypeofOwnership:"Freehold",
       Overlooking:"Main Road",
       AgeofConstruction:"1 to 5 years",
       WaterAvailability:"24 Hours Available",
       StatusofElectricity:"No/Rare Powercut",   
       AuthorityApproval:"Developer",
       },
   ]